CREATE TABLE IF NOT EXISTS racing_details(
   record_type   varchar(2),
   data_div   varchar(1),
   data_create_date   date,
   race_id     varchar(16),
   holding_date     date,
   course_cd     varchar(15),
   holding_no     integer,
   holding_day     integer,
   race_no     integer,
   week_day_cd     varchar(15),
   special_race_no     integer,
   race_name_full     varchar(60),
   race_name_sub     varchar(60),
   race_name_note     varchar(60),
   race_name_full_eng     varchar(120),
   race_name_sub_eng     varchar(120),
   race_name_note_eng     varchar(120),
   race_name_short_char10     varchar(20),
   race_name_short_char6     varchar(12),
   race_name_short_char3     varchar(6),
   race_name_div     integer,
   grade_times     integer,
   grade_cd     varchar(15),
   grade_cd_before     varchar(15),
   race_type_cd     varchar(15),
   race_sign_cd     varchar(15),
   weight_type_cd     varchar(15),
   race_condition_cd_old2     integer,
   race_condition_cd_old3     integer,
   race_condition_cd_old4     integer,
   race_condition_cd_old5     integer,
   race_condition_cd_youngest     integer,
   race_condition_name     varchar(60),
   distance     varchar(4),
   distance_before     varchar(4),
   track_cd     varchar(15),
   track_cd_before     varchar(15),
   course_div     varchar(2),
   course_div_before     varchar(2),
   added_money_items     integer[],
   added_money_before_items     integer[],
   stakes_money_items     integer[],
   stakes_money_before_items     integer[],
   start_time     varchar(4),
   start_time_before     varchar(4),
   entry_count     varchar(2),
   starter_count     varchar(2),
   finished_count     varchar(2),
   weather_cd     varchar(15),
   turf_condition_cd     varchar(15),
   dirt_condition_cd     varchar(15),
   lap_time_items     time[],
   jump_mile_time     time,
   first_furlong3     time,
   first_furlong4     time,
   last_furlong3     time,
   last_furlong4     time,
   corner_passage_ranks     jsonb[],
   record_update_div     varchar(1),
   PRIMARY KEY(race_id)
);

--ALTER TABLE racing_details DROP COLUMN corner_passage_ranks;
--ALTER TABLE racing_details ADD COLUMN corner_passage_ranks jsonb[];
--ALTER TABLE racing_details ALTER COLUMN corner_passage_ranks TYPE jsonb[];