mongo:
  host: 10.0.2.2
  port: 27017
  database: test


setup:
  yyyyMMddHHmmss: 2019/01/01 00:00:00
  dataTypes:
    - RacingDetails
    - HorseRacingDetails
    - RaceRefund
    - VoteCount
    - WinsPlaceBracketQuinella
    - Quinella
    - Ancestry
    - BreedingHorse
    - Offspring
    - RaceHorse
    - Jockey
    - Trainer
    - Owner
    - Breeder
    - Course
